platform :ios, '12.0'

# Main pods

def main
  pod 'SwiftyJSON', '5.0.0'
  pod 'RxSwift', '5.1.1'
  pod 'RxCocoa', '5.1.1'
  pod 'VK-ios-sdk', '1.5.1'
  pod 'SDWebImage', '5.8.0'
  pod 'ObjectMapper', '4.2.0'
  pod 'PKHUD', '5.3.0'
end

# Pods for SwiftFriendsListVK target

target 'SwiftFriendsListVK' do
  use_frameworks!
  main
end

# Pods for SwiftFriendsListVKTests target

target 'SwiftFriendsListVKTests' do
    use_frameworks!
    main
end
