# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftFriendsListVK' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftFriendsListVK
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'VK-ios-sdk'
  pod 'SDWebImage', '~> 4.0'
  pod 'ObjectMapper', '~> 3.2'
  pod 'PKHUD', '~> 5.0'

end
